service: nodejs-elasticsearch-example

app: NodeEsExample

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

functions:
  createProfile:
    handler: handler.createProfile
    events:
      - http:
          path: api/v1/profiles/
          method: post
  updateProfile:
    handler: handler.updateProfile
    events:
      - http:
          path: api/v1/profiles/{Id}
          method: put

  findAllProfile:
    handler: handler.findAllProfile
    events:
      - http:
          path: api/v1/profiles/
          method: get

  findByTitle:
    handler: handler.findByTitle
    events:
      - http:
          path: api/v1/profiles/auto-complete/{title}
          method: get

  findProfileById:
    handler: handler.findProfileById
    events:
      - http:
          path: api/v1/profiles/{Id}
          method: get

  deleteProfileById:
    handler: handler.deleteProfileById
    events:
      - http:
          path: api/v1/profiles/{Id}
          method: delete

  nestedQueryExample:
    handler: handler.nestedQueryExample
    events:
      - http:
          path: api/v1/profiles/nested-query/{skils}
          method: get

  getProfileCount:
    handler: handler.getProfileCount
    events:
      - http:
          path: api/v1/profiles/counts
          method: get

plugins:
  - serverless-offline
