service: nodejs-elasticsearch-example

app: NodeEsExample

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

functions:

  createProfile:
    handler: handler.createProfile
    events:
      - http:
         path: profiles
         method: post

  findAllProfile:
    handler: handler.findAllProfile
    events:
      - http:
          path: profiles
          method: get

  findByTitle:
    handler: handler.findByTitle
    events:
      - http:
          path: profiles/autocomplete/{title}
          method: get

  findProfileById:
    handler: handler.findProfileById
    events:
      - http:
         path: profiles/{Id}
         method: get


plugins:
  - serverless-offline